# Generated by Django 5.2.7 on 2026-02-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='ecommerce.campaign'),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_products', to='ecommerce.campaignparticipation'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='coupons_by_category', to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='ecommerce.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationservice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_education_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.loyaltypointsconfig'),
        ),
        migrations.AddField(
            model_name='loyaltypointstransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons_by_product', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='products',
            field=models.ManyToManyField(through='ecommerce.CampaignProduct', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productstock'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productstock'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ecommerce.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.subcategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='coupons_by_subcategory', to='ecommerce.subcategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ecommerce.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('service_type', 'subscription_type')},
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategories', to='ecommerce.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.subsubcategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='subsubcategories',
            field=models.ManyToManyField(blank=True, related_name='coupons_by_subsubcategory', to='ecommerce.subsubcategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='ecommerce.subsubcategory'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='educationservice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_services', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor who created this coupon', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='selected_vendors',
            field=models.ManyToManyField(blank=True, help_text='Vendors selected for participation', related_name='selected_campaigns', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='vendorapprovalrequest',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='vendorwallet',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='ecommerce.vendor'),
        ),
        migrations.AddField(
            model_name='vendorwithdrawalrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='ecommerce.vendor'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='ecommerce_c_coupon__b2a4d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignproduct',
            unique_together={('participation', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'product_stock')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subsubcategory',
            unique_together={('subcategory', 'name')},
        ),
        migrations.AddIndex(
            model_name='educationservice',
            index=models.Index(fields=['vendor', 'status'], name='ecommerce_e_vendor__18e858_idx'),
        ),
        migrations.AddIndex(
            model_name='educationservice',
            index=models.Index(fields=['city', 'education_type'], name='ecommerce_e_city_9dfa74_idx'),
        ),
        migrations.AddIndex(
            model_name='educationservice',
            index=models.Index(fields=['status', 'is_active'], name='ecommerce_e_status_b082f4_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='ecommerce_c_code_bd5447_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['vendor', 'status'], name='ecommerce_c_vendor__cf6cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'expire_date'], name='ecommerce_c_start_d_12855c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipation',
            unique_together={('campaign', 'vendor')},
        ),
    ]
