# Generated by Django 5.2.7 on 2026-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignproduct',
            name='banner_button_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for hero section (1970x700 pixels)', null=True, upload_to='deal_of_day_banners/'),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='campaignproduct',
            name='banner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
