# Generated by Django 5.2.7 on 2026-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_campaignproduct_banner_button_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignparticipation',
            name='discount_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='is_banner_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignparticipation',
            name='vendor_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
