# Generated by Django 5.2.7 on 2026-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_campaignparticipation_discount_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
