# Generated by Django 5.2.7 on 2026-02-17 06:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_category_featured_order_category_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-web_home', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='platform_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform charge percentage for products in this category', max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='web_home',
            field=models.BooleanField(default=False, help_text='Show this category on homepage sliders'),
        ),
    ]
