# Generated by Django 5.2.7 on 2026-02-27 05:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_product_description_features_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='platform_charge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform charge percentage at time of product creation', max_digits=5),
        ),
        migrations.AddField(
            model_name='productstock',
            name='vendor_receivable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount vendor receives after platform charge', max_digits=10),
        ),
    ]
