# Generated by Django 5.2.7 on 2026-02-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_productstock_platform_charge_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_service', models.CharField(choices=[('shipmojo', 'ShipMojo (Recommended)'), ('self', 'Self Delivery'), ('courier', 'Courier Service')], default='self', max_length=20)),
                ('delivery_man_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_man_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_incentive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_website', models.URLField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed to Deliver'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_deliveries', to='ecommerce.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_infos', to='ecommerce.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Delivery Information',
                'verbose_name_plural': 'Vendor Delivery Information',
                'unique_together': {('order', 'vendor')},
            },
        ),
    ]
