# Generated by Django 5.2.7 on 2026-03-03 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_vendordeliveryinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('billing_address_id', models.IntegerField(blank=True, null=True)),
                ('shipping_address_id', models.IntegerField(blank=True, null=True)),
                ('use_same_address', models.BooleanField(default=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('loyalty_points_to_use', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
