# Generated by Django 5.2.7 on 2026-03-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_pendingcheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcheckout',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
