# Generated by Django 5.2.7 on 2026-03-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_pendingcheckout_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcheckout',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingcheckout',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
