# Generated by Django 5.2.7 on 2026-03-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_pendingcheckout_payment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcheckout',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
