# Generated by Django 5.2.7 on 2026-03-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_order_ecommerce_o_created_86a742_idx_and_more'),
        ('mlm', '0010_mlmsettings_agent_is_active_agent_agent_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mlm.agent'),
        ),
    ]
