# Generated by Django 5.2.7 on 2026-03-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_order_referral_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
