# Generated by Django 5.2.7 on 2026-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_orderitem_final_price_orderitem_platform_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mlm_commission_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingcheckout',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
