# Generated by Django 5.2.7 on 2026-03-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_order_mlm_commission_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='platform_profit',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_receivable',
        ),
    ]
