# Generated by Django 5.2.7 on 2026-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_remove_orderitem_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
