# Generated by Django 5.2.7 on 2026-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_orderitem_final_price_orderitem_platform_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
