# Generated by Django 5.2.7 on 2026-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_order_commission_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_commission_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_distributed_at_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_distributed_at_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_commission_processed',
            field=models.BooleanField(default=False),
        ),
    ]
