# Generated by Django 5.2.7 on 2026-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_order_checkout_commission_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='eligible_for_agent_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_eligible_for_agent',
            field=models.BooleanField(default=False),
        ),
    ]
