# Generated by Django 5.2.7 on 2026-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_customerprofile_eligible_for_agent_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='agent_documents_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='agent_documents_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
