# Generated by Django 5.2.7 on 2026-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_customerprofile_agent_documents_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='id_proof_temp',
            field=models.FileField(blank=True, null=True, upload_to='temp/agents/idproof/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='passport_photo_temp',
            field=models.ImageField(blank=True, null=True, upload_to='temp/agents/photos/'),
        ),
    ]
