# Generated by Django 5.2.7 on 2026-03-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_customerprofile_id_proof_temp_and_more'),
    ]

    operations = [
    ]
