# Generated by Django 5.2.7 on 2026-03-31 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_fix_customer_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('user', 'email'), name='unique_user_email'),
        ),
    ]
