# Generated by Django 5.2.7 on 2026-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_us_pdf', models.FileField(blank=True, help_text='Upload Contact Us PDF', null=True, upload_to='documents/')),
                ('privacy_policy_pdf', models.FileField(blank=True, help_text='Upload Privacy Policy PDF', null=True, upload_to='documents/')),
                ('terms_conditions_pdf', models.FileField(blank=True, help_text='Upload Terms & Conditions PDF', null=True, upload_to='documents/')),
                ('refund_cancellation_pdf', models.FileField(blank=True, help_text='Upload Refund & Cancellation PDF', null=True, upload_to='documents/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
