# Generated by Django 5.2.7 on 2026-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_sitedocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedocument',
            old_name='refund_cancellation_pdf',
            new_name='return_cancellation_pdf',
        ),
        migrations.AddField(
            model_name='sitedocument',
            name='refund_pdf',
            field=models.FileField(blank=True, help_text='Upload Return PDF', null=True, upload_to='documents/'),
        ),
    ]
