# Generated by Django 5.2.7 on 2026-07-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_rename_refund_cancellation_pdf_sitedocument_return_cancellation_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_platform_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cod_platform_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_platform_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('release_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ManyToManyField(blank=True, related_name='payment_requests', to='ecommerce.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='ecommerce.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorCODRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.orderitem')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cod_recoveries', to='ecommerce.vendorpaymentrequest')),
            ],
            options={
                'unique_together': {('order_item',)},
            },
        ),
    ]
