# Generated by Django 5.2.7 on 2026-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_vendorpaymentrequest_vendorcodrecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='approved_online_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='approved_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='approved_orders',
            field=models.ManyToManyField(blank=True, related_name='approved_payment_requests', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentrequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
