# Generated by Django 5.2.7 on 2026-07-28 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_vendorpaymentrequest_admin_remarks_and_more'),
        ('mlm', '0016_agent_is_pos_branch_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='ecommerce_o_deliver_45f667_idx'),
        ),
    ]
