# Generated by Django 5.2.7 on 2026-08-26 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_qrcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged Product'), ('wrong_item', 'Wrong Item Delivered'), ('not_as_described', 'Not as Described'), ('size_issue', 'Size/Fit Issue'), ('quality_issue', 'Quality Issue'), ('changed_mind', 'Changed My Mind'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('re_requested', 're-Requested'), ('admin_approved', 'Admin Approved'), ('admin_rejected', 'Admin Rejected')], default='requested', max_length=20)),
                ('vendor_remarks', models.TextField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('re_requested_at', models.DateTimeField(blank=True, null=True)),
                ('admin_responded_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='ecommerce.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='ecommerce.orderitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='ecommerce.vendor')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
