# Generated by Django 5.2.7 on 2026-08-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='ecommerce.returnrequest')),
            ],
        ),
    ]
