# Generated by Django 5.2.7 on 2026-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_orderrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='commission_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
