# Generated by Django 5.2.7 on 2026-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_orderrefund_commission_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mlm_commission_processed',
            field=models.BooleanField(default=True),
        ),
    ]
