# Generated by Django 5.2.7 on 2026-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_orderitem_mlm_commission_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='mlm_commission_processed',
            field=models.BooleanField(default=False),
        ),
    ]
