# Generated by Django 5.2.7 on 2026-05-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile/banners/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MobileCategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_start', models.CharField(default='#E8F4FD', max_length=20)),
                ('gradient_end', models.CharField(default='#BBDEFB', max_length=20)),
                ('accent_color', models.CharField(default='#1565C0', max_length=20)),
                ('header_color', models.CharField(default='#1565C0', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_cards', to='ecommerce.subcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MobileDealCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('flash', 'Flash Deal'), ('featured', 'Featured Deal')], default='flash', max_length=20)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0)),
                ('gradient_start', models.CharField(default='#FFF3E0', max_length=20)),
                ('gradient_end', models.CharField(default='#FFE0B2', max_length=20)),
                ('accent_color', models.CharField(default='#E65100', max_length=20)),
                ('header_color', models.CharField(default='#BF360C', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_deal_cards', to='ecommerce.product')),
            ],
            options={
                'ordering': ['deal_type', 'order'],
            },
        ),
    ]
