# Generated by Django 5.2.7 on 2026-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_mobilebanner_mobilecategorycard_mobiledealcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='mobilebanner',
            table='mobile_banner',
        ),
    ]
