# Generated by Django 5.2.7 on 2026-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_mobilebanner_updated_at_alter_mobilebanner_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebanner',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='button_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile/banners/'),
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
