# Generated by Django 5.2.7 on 2026-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_mobilebanner_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminprofile',
            name='brochure_pdf',
            field=models.FileField(blank=True, help_text='Upload company brochure (PDF only)', null=True, upload_to='brochures/'),
        ),
    ]
