# Generated by Django 5.2.7 on 2026-09-01 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_superadminprofile_brochure_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadminprofile',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Upload Android app APK file', null=True, upload_to='app_apk/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])]),
        ),
    ]
