# Generated by Django 5.2.7 on 2026-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
