# Generated by Django 5.2.7 on 2026-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_branch_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='BR',
            field=models.CharField(blank=True, default='BR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='CR',
            field=models.CharField(blank=True, default='CR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gst_toggle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
