# Generated by Django 5.2.7 on 2026-02-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_setting_br_alter_setting_cr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_logged_in',
            field=models.BooleanField(default=True),
        ),
    ]
