# Generated by Django 5.2.7 on 2026-02-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_branch_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
