# Generated by Django 5.2.7 on 2026-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_branch_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
