# Generated by Django 5.2.7 on 2026-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_branch_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='PCP',
            field=models.CharField(blank=True, default='PCP', max_length=10, null=True),
        ),
    ]
