# Generated by Django 5.2.7 on 2026-03-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_setting_pcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='PBP',
            field=models.CharField(blank=True, default='PBP', max_length=50, null=True),
        ),
    ]
