# Generated by Django 5.2.7 on 2026-03-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_setting_pbp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='PBP',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='PCP',
        ),
    ]
