# Generated by Django 5.2.7 on 2026-03-26 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_setting_pbp_remove_setting_pcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='mode',
        ),
        migrations.AddField(
            model_name='bankreceipt',
            name='sales_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.salesmaster'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='sales_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.salesmaster'),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='pos.account'),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='mode',
            field=models.CharField(choices=[('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='op_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipt_op_accounts', to='pos.account'),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='type',
            field=models.CharField(choices=[('BR', 'Bank Receipt'), ('SBR', 'Sales Bank Receipt')], default='BR', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='voucher_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='pos.account'),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='op_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipt_op_accounts', to='pos.account'),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='type',
            field=models.CharField(choices=[('CR', 'Cash Receipt'), ('SCR', 'Sales Cash Receipt')], default='CR', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='voucher_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
