# Generated by Django 5.2.7 on 2026-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_cashreceipt_mode_bankreceipt_sales_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='bill_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
