# Generated by Django 5.2.7 on 2026-03-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_purchasereturnmaster_purchasereturnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='party',
            field=models.ForeignKey(limit_choices_to={'group': 'Supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='pos.account'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='return_type',
            field=models.CharField(choices=[('Full', 'Full Return'), ('Partial', 'Partial Return')], max_length=20),
        ),
    ]
