# Generated by Django 5.2.7 on 2026-03-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_alter_purchasereturnitem_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.purchaseitem'),
        ),
    ]
