# Generated by Django 5.2.7 on 2026-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_purchasereturnitem_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='PR',
            field=models.CharField(blank=True, default='PR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='SR',
            field=models.CharField(blank=True, default='SR', max_length=50, null=True),
        ),
    ]
