# Generated by Django 5.2.7 on 2026-03-27 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_purchasereturnitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
