# Generated by Django 5.2.7 on 2026-03-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_salesitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pos.salesitem'),
        ),
    ]
