# Generated by Django 5.2.7 on 2026-03-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_salesreturnitem_sales_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreceipt',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='pos.purchasereturnmaster'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='pos.purchasereturnmaster'),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'Bank Account'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_bank', to='pos.account'),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='cash_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'Case In Hand'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_cash', to='pos.account'),
        ),
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
