# Generated by Django 5.2.7 on 2026-03-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_customerprofile_agent_documents_uploaded_and_more'),
        ('pos', '0020_bankreceipt_purchase_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description_features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_items', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='items',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/product_images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='product_condition',
            field=models.CharField(blank=True, default='New', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='return_policy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='specifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/product_images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='warranty_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='warranty_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='warranty_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='website_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved & Live'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
