# Generated by Django 5.2.7 on 2026-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_items_description_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariants',
            name='variant_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/variant_images/'),
        ),
    ]
