# Generated by Django 5.2.7 on 2026-04-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_itemvariants_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='website_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved '), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
