# Generated by Django 5.2.7 on 2026-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_alter_items_website_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
