# Generated by Django 5.2.7 on 2026-04-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_itemgroup_alter_items_group_itemunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='pos.salesreturnmaster'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='pos.salesreturnmaster'),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'Bank Account'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_bank', to='pos.account'),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='cash_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'group': 'Case In Hand'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_cash', to='pos.account'),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
