# Generated by Django 5.2.7 on 2026-04-06 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_bankpayment_sales_return_cashpayment_sales_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='pos.purchasemaster'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='pos.purchasemaster'),
        ),
    ]
