# Generated by Django 5.2.7 on 2026-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_bankpayment_purchase_cashpayment_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariants',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
