# Generated by Django 5.2.7 on 2026-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_alter_itemvariants_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='voucher_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contra',
            unique_together={('branch', 'voucher_no')},
        ),
    ]
