# Generated by Django 5.2.7 on 2026-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_alter_contra_voucher_no_alter_contra_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmaster',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='bill_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='salesmaster',
            unique_together={('branch', 'bill_no')},
        ),
    ]
