# Generated by Django 5.2.7 on 2026-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_salesmaster_cancelled_at_salesmaster_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='bill_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
