# Generated by Django 5.2.7 on 2026-04-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_alter_salesmaster_bill_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesmaster',
            constraint=models.UniqueConstraint(fields=('branch', 'bill_no'), name='unique_bill_per_branch'),
        ),
    ]
    
