# Generated by Django 5.2.7 on 2026-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_fix_branch_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemunit',
            options={'ordering': ['unit_type', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='itemunit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='conversion_to_base',
            field=models.FloatField(default=1.0, help_text='Conversion factor to base unit (e.g., g -> kg = 0.001)'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='supports_fractional',
            field=models.BooleanField(default=False, help_text='True for weight/volume units like kg, ltr where 10kg @300 => 1kg @30'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='unit_type',
            field=models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('count', 'Count'), ('area', 'Area'), ('other', 'Other')], default='count', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemunit',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='itemunit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemunit',
            name='description',
        ),
    ]
