# Generated by Django 5.2.7 on 2026-05-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_predefined_units_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='area',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='account',
            name='anniversary',
        ),
        migrations.RemoveField(
            model_name='account',
            name='birthday_on',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
