# Generated by Django 5.2.7 on 2026-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_rename_area_account_country_remove_account_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreceipt',
            name='type',
            field=models.CharField(choices=[('BR', 'Bank Receipt'), ('SBR', 'Sales Bank Receipt'), ('PRBR', 'Purchase Return Bank Receipt')], default='BR', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='type',
            field=models.CharField(choices=[('CR', 'Cash Receipt'), ('SCR', 'Sales Cash Receipt'), ('PRCR', 'Purchase Return Cash Receipt')], default='CR', max_length=10),
        ),
    ]
