# Generated by Django 5.2.7 on 2026-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_alter_bankreceipt_type_alter_cashreceipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sales_gst_toggle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
