# Generated by Django 5.2.7 on 2026-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_setting_sales_gst_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnmaster',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
