# Generated by Django 5.2.7 on 2026-05-29 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_purchasereturnmaster_duedate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='pos.branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='pos.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_item_name', models.CharField(max_length=255)),
                ('from_variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('from_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('to_item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('to_variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('match_by', models.CharField(choices=[('barcode', 'Barcode'), ('name_variant', 'Name + Size/Color'), ('name', 'Name Only'), ('manual', 'Manually Mapped'), ('unmatched', 'Not Matched')], default='unmatched', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('is_stock_updated', models.BooleanField(default=False)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_outgoing_items', to='pos.items')),
                ('from_variant', models.ForeignKey(help_text='Specific variant being transferred', on_delete=django.db.models.deletion.PROTECT, related_name='transfer_outgoing', to='pos.itemvariants')),
                ('to_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_incoming_items', to='pos.items')),
                ('to_variant', models.ForeignKey(blank=True, help_text='Matched variant in receiving branch (null = not matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_incoming', to='pos.itemvariants')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.stocktransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
