# Generated by Django 5.2.7 on 2026-06-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_stocktransfer_stocktransferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ST',
            field=models.CharField(blank=True, default='ST', max_length=50, null=True),
        ),
    ]
