# Generated by Django 5.2.7 on 2026-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0041_setting_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='created_by_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
