# Generated by Django 5.2.7 on 2026-06-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0042_items_created_by_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='match_by',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='to_item',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='to_item_name',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='to_variant',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='to_variant_info',
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='from_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_outgoing', to='pos.itemvariants'),
        ),
    ]
