# Generated by Django 5.2.7 on 2026-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0043_remove_stocktransferitem_match_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariants',
            name='branchPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='website_display_on_verify',
            field=models.BooleanField(default=False),
        ),
    ]
