# Generated by Django 5.2.7 on 2026-06-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0044_itemvariants_branchprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferitem',
            name='to_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_incoming', to='pos.itemvariants'),
        ),
    ]
