# Generated by Django 5.2.7 on 2026-06-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_stocktransferitem_to_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='gst_toggle_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
