# Generated by Django 5.2.7 on 2026-06-13 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0046_salesitem_gst_toggle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partially_sent', 'Partially Sent'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_orders', to='pos.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('linked_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orders', to='pos.stocktransfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('hsnCode', models.CharField(blank=True, max_length=50, null=True)),
                ('taxSlab', models.CharField(blank=True, max_length=20, null=True)),
                ('global_item_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('requested_quantity', models.IntegerField(default=0)),
                ('approved_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('is_removed_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.branchorder')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_references', to='pos.items')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_references', to='pos.itemvariants')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
