# Generated by Django 5.2.7 on 2026-06-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0047_branchorder_branchorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to='pos.branchorder'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('manual', 'Manual Transfer'), ('order', 'Order Transfer')], default='manual', max_length=10),
        ),
    ]
