# Generated by Django 5.2.7 on 2026-06-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0048_stocktransfer_source_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchorderitem',
            name='branch_price',
            field=models.FloatField(default=0),
        ),
    ]
