# Generated by Django 5.2.7 on 2026-06-17 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0049_branchorderitem_branch_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSProfitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_in_toggle', models.BooleanField(default=True, help_text='ON = Walk-in simple split (90% branch, 10% company). OFF = MLM distribution mode (referral code required).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POS Profit Settings',
                'verbose_name_plural': 'POS Profit Settings',
            },
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='mlm_commission_processed',
            field=models.BooleanField(default=False, help_text='True = MLM commission already distribute ho gaya'),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='referral_agent',
            field=models.ForeignKey(blank=True, help_text='Agent jiska referral code use hua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_referred_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Customer ne jo referral code diya sale ke time', max_length=20, null=True),
        ),
    ]
