# Generated by Django 5.2.7 on 2026-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0051_stockreturn_stockreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, help_text='3-letter branch code', max_length=3, null=True, unique=True),
        ),
    ]
