# Generated by Django 5.2.7 on 2026-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0053_ordersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Return Sequence',
                'verbose_name_plural': 'Return Sequences',
            },
        ),
    ]
