# Generated by Django 5.2.7 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0057_seed_order_sequence_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='stock_transfer_gst_toggle',
            field=models.BooleanField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='basic_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='tax_percent',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
