# Generated by Django 5.2.7 on 2026-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0058_setting_stock_transfer_gst_toggle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchorderitem',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='branchorderitem',
            name='tax_percent',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
