# Generated by Django 5.2.7 on 2026-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0059_branchorderitem_basic_amount_branchorderitem_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
