# Generated by Django 5.2.7 on 2026-07-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0062_bankreceipt_stock_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreceipt',
            name='stock_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='pos.stocktransfer'),
        ),
    ]
