# Generated by Django 5.2.7 on 2026-07-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0063_alter_bankreceipt_stock_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Bank Account', 'Bank Account'), ('Case In Hand', 'Case In Hand'), ('Customer - Sundry Debitor', 'Customer - Sundry Debitor'), ('Supplier - Sundry Creditor', 'Supplier - Sundry Creditor'), ('Sundry Debitor(Internal)', 'Sundry Debitor(Internal)'), ('Sundry Creditor(Internal)', 'Sundry Creditor(Internal)')], max_length=50),
        ),
    ]
