# Generated by Django 5.2.7 on 2026-07-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0064_alter_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sundry_creditor_account',
            field=models.OneToOneField(blank=True, help_text="Account representing this branch as a creditor (payable) for other branches' books", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_creditor_branch', to='pos.account'),
        ),
        migrations.AddField(
            model_name='branch',
            name='sundry_debitor_account',
            field=models.OneToOneField(blank=True, help_text="Account representing this branch as a debitor (receivable) for other branches' books", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_debitor_branch', to='pos.account'),
        ),
    ]
