# Generated by Django 5.2.7 on 2026-07-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0066_alter_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='stock_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payments', to='pos.stocktransfer'),
        ),
        migrations.AddField(
            model_name='cashpayment',
            name='stock_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to='pos.stocktransfer'),
        ),
    ]
