# Generated by Django 5.2.7 on 2026-07-13 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0067_bankpayment_stock_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreceipt',
            name='stock_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_receipts', to='pos.stockreturn'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='stock_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='pos.stockreturn'),
        ),
        migrations.AlterField(
            model_name='bankreceipt',
            name='type',
            field=models.CharField(choices=[('BR', 'Bank Receipt'), ('SBR', 'Sales Bank Receipt'), ('PRBR', 'Purchase Return Bank Receipt'), ('STBR', 'Stock Transfer Bank Receipt'), ('STRBR', 'Stock Return Bank Receipt')], default='BR', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='type',
            field=models.CharField(choices=[('CR', 'Cash Receipt'), ('SCR', 'Sales Cash Receipt'), ('PRCR', 'Purchase Return Cash Receipt'), ('STCR', 'Stock Transfer Cash Receipt'), ('STRCR', 'Stock Return Cash Receipt')], default='CR', max_length=10),
        ),
    ]
