# Generated by Django 5.2.7 on 2026-07-14 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0068_bankreceipt_stock_return_cashreceipt_stock_return_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'B2B Order Sequence',
            },
        ),
        migrations.CreateModel(
            name='B2BTransferSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'B2B Transfer Sequence',
            },
        ),
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('partially_sent', 'Partially Sent'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_b2b_orders', to=settings.AUTH_USER_MODEL)),
                ('requesting_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders_placed', to='pos.branch')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders_received', to='pos.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('hsnCode', models.CharField(blank=True, max_length=50, null=True)),
                ('taxSlab', models.CharField(blank=True, max_length=20, null=True)),
                ('global_item_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('requested_quantity', models.IntegerField(default=0)),
                ('approved_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('sent_quantity', models.IntegerField(default=0)),
                ('is_removed_by_admin', models.BooleanField(default=False)),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_price', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('tax_percent', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('basic_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_transferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.b2border')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_order_references', to='pos.items')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_order_references', to='pos.itemvariants')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='B2BStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfers_sent', to='pos.branch')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to='pos.b2border')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfers_received', to='pos.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='b2border',
            name='linked_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orders', to='pos.b2bstocktransfer'),
        ),
        migrations.CreateModel(
            name='B2BStockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_item_name', models.CharField(max_length=255)),
                ('from_variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('from_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('is_stock_updated', models.BooleanField(default=False)),
                ('tax_percent', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfer_outgoing_items', to='pos.items')),
                ('from_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_transfer_outgoing', to='pos.itemvariants')),
                ('to_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_transfer_incoming', to='pos.itemvariants')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.b2bstocktransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
