# Generated by Django 5.2.7 on 2026-07-14 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0069_b2bordersequence_b2btransfersequence_b2border_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b2bordersequence',
            options={},
        ),
        migrations.AlterModelOptions(
            name='b2btransfersequence',
            options={},
        ),
        migrations.RenameField(
            model_name='b2borderitem',
            old_name='sent_quantity',
            new_name='available_quantity',
        ),
        migrations.RenameField(
            model_name='b2borderitem',
            old_name='is_removed_by_admin',
            new_name='is_removed',
        ),
        migrations.RenameField(
            model_name='b2bstocktransferitem',
            old_name='is_stock_updated',
            new_name='is_packaged',
        ),
        migrations.RemoveField(
            model_name='b2borderitem',
            name='is_transferred',
        ),
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_confirmed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='packaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_packaged_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bstocktransferitem',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('no_stock', 'No Stock'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='b2borderitem',
            name='approved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='b2bstocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packaging_ready', 'Packaging Ready'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='b2bstocktransferitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
