# Generated by Django 5.2.7 on 2026-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0070_alter_b2bordersequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='credit_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
