# Generated by Django 5.2.7 on 2026-07-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0071_branch_credit_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('availability', models.CharField(choices=[('all', 'All Branch'), ('selected', 'Selected Branch')], default='all', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheme_type', models.CharField(choices=[('per_month', 'Per Month')], default='per_month', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='scheme_offers', to='pos.branch')),
                ('created_by_branch', models.ForeignKey(blank=True, help_text='Main branch (superadmin) that created this scheme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to='pos.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
