# Generated by Django 5.2.7 on 2026-07-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0072_schemeoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bstocktransfer',
            name='packaging_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_packaging_started_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='b2bstocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packaging_start', 'Packaging Started'), ('packaging_ready', 'Packaging Ready'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
