# Generated by Django 5.2.7 on 2026-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0073_b2bstocktransfer_packaging_started_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bstocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packaging_start', 'Packaging Started'), ('packaging_ready', 'Packaging Ready'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
