# Generated by Django 5.2.7 on 2026-07-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0074_alter_b2bstocktransfer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
