# Generated by Django 5.2.7 on 2026-07-20 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0075_account_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BReturnSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'B2B Return Sequence',
                'verbose_name_plural': 'B2B Return Sequences',
            },
        ),
        migrations.CreateModel(
            name='B2BStockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packaging_ready', 'Packaging Ready'), ('approved', 'Approved'), ('received', 'Received'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_b2b_returns', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_stock_returns_sent', to='pos.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_b2b_returns', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_b2b_returns', to=settings.AUTH_USER_MODEL)),
                ('source_b2b_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='pos.b2bstocktransfer')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_stock_returns_received', to='pos.branch')),
            ],
            options={
                'verbose_name': 'B2B Stock Return',
                'verbose_name_plural': 'B2B Stock Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BStockReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('variant_info', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('hsnCode', models.CharField(blank=True, max_length=50, null=True)),
                ('taxSlab', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_percent', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('basic_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('is_packaging_ready', models.BooleanField(default=False)),
                ('is_returned_to_company', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_returned_items_from_branch', to='pos.itemvariants')),
                ('company_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_returned_items_to_company', to='pos.itemvariants')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.b2bstockreturn')),
                ('source_b2b_transfer_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='pos.b2bstocktransferitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
