# Generated by Django 5.2.7 on 2026-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0076_b2breturnsequence_b2bstockreturn_b2bstockreturnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBillDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('main', 'Main Branch (Superadmin)'), ('branch', 'Selected Branches')], default='branch', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_branches', models.ManyToManyField(blank=True, related_name='sales_bill_display_settings', to='pos.branch')),
            ],
        ),
    ]
