# Generated by Django 5.2.7 on 2026-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0077_salesbilldisplaysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='ownership_type',
            field=models.CharField(choices=[('branch', 'Branch'), ('franchise', 'Franchise')], default='branch', help_text='Is this a Branch or Franchise?', max_length=20),
        ),
    ]
