# Generated by Django 5.2.7 on 2026-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0080_bankreceipt_b2b_sale_cashreceipt_b2b_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreceipt',
            name='type',
            field=models.CharField(choices=[('BR', 'Bank Receipt'), ('SBR', 'Sales Bank Receipt'), ('PRBR', 'Purchase Return Bank Receipt'), ('STBR', 'Stock Transfer Bank Receipt'), ('STRBR', 'Stock Return Bank Receipt'), ('B2BSBR', 'B2B Sale Bank Receipt')], default='BR', max_length=10),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='type',
            field=models.CharField(choices=[('CR', 'Cash Receipt'), ('SCR', 'Sales Cash Receipt'), ('PRCR', 'Purchase Return Cash Receipt'), ('STCR', 'Stock Transfer Cash Receipt'), ('STRCR', 'Stock Return Cash Receipt'), ('B2BSCR', 'B2B Sale Cash Receipt')], default='CR', max_length=10),
        ),
    ]
