# Generated by Django 5.2.7 on 2026-07-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0081_alter_bankreceipt_type_alter_cashreceipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='b2b_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_entry', to='pos.b2bsale'),
        ),
    ]
