# Generated by Django 5.2.7 on 2026-07-31 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0082_purchasemaster_b2b_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantBranchMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dest_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mapping', to='pos.itemvariants')),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_mappings', to='pos.itemvariants')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_mappings', to='pos.branch')),
            ],
            options={
                'unique_together': {('source_variant', 'to_branch')},
            },
        ),
    ]
