# Generated by Django 5.2.7 on 2026-08-06 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0083_variantbranchmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariants',
            name='mrp',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator]),
        ),
        migrations.AlterField(
            model_name='itemvariants',
            name='opStock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itemvariants',
            name='purchasePrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator]),
        ),
        migrations.AlterField(
            model_name='itemvariants',
            name='salesPrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator]),
        ),
    ]
