# Generated by Django 5.2.7 on 2026-08-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0084_alter_itemvariants_mrp_alter_itemvariants_opstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='frightcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='otherexpnse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='roundamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
