# Generated by Django 5.2.7 on 2026-08-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0086_employee_employeepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='voucher_no',
            field=models.CharField(max_length=50),
        ),
    ]
