# Generated by Django 5.2.7 on 2026-08-22 07:23

import pos.models.branch
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0101_aipurchasedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to=pos.models.branch.branch_pancard_path),
        ),
        migrations.AddField(
            model_name='branch',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=10, null=True),
        ),
    ]
