# Generated by Django 5.2.7 on 2026-08-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0102_branch_gst_number_branch_pan_card_branch_pan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent_franchise',
            field=models.ForeignKey(blank=True, help_text='Set ONLY when this Branch was created BY a Franchise (2-level hierarchy: Superadmin → Franchise → Branch). Null for top-level Branch/Franchise rows created by Superadmin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_branches', to='pos.branch'),
        ),
    ]
