# Generated by Django 5.2.7 on 2026-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0103_branch_parent_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
