# Generated by Django 5.2.7 on 2026-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0104_stocktransferitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariants',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
