# Generated by Django 5.2.7 on 2026-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0105_alter_itemvariants_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemName',
            field=models.CharField(max_length=150),
        ),
    ]
