# Generated by Django 5.2.7 on 2026-09-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0106_alter_items_itemname'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantPurchasePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('new_price', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_price_history', to='pos.itemvariants')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
