# Generated by Django 5.2.7 on 2026-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0107_variantpurchasepricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2bsaleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
