# Generated by Django 5.2.7 on 2026-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0108_alter_b2bsaleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
