# Generated by Django 5.2.7 on 2026-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mlm_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
