# Generated by Django 5.2.7 on 2026-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0002_remove_profitdistribution_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
    ]
