# Generated by Django 5.2.7 on 2026-03-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_mlmlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default MLM Config', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mlmlevel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mlmlevel',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mlm.mlmlevelconfig'),
        ),
    ]
