# Generated by Django 5.2.7 on 2026-03-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_mlmlevelconfig_remove_mlmlevel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmlevel',
            name='config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mlm.mlmlevelconfig'),
            preserve_default=False,
        ),
    ]
