# Generated by Django 5.2.7 on 2026-03-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_agent_agentbankdetails_user_agent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='sponsor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
