# Generated by Django 5.2.7 on 2026-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0007_alter_agent_user_remove_agent_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('normal', 'Normal Agent'), ('pos', 'POS Agent'), ('society', 'Society Agent')], max_length=20),
        ),
    ]
