# Generated by Django 5.2.7 on 2026-03-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0009_agent_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='is_active_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
