# Generated by Django 5.2.7 on 2026-03-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_customerprofile_id_proof_temp_and_more'),
        ('mlm', '0011_agentwallet_mlmtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='minimum_achieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='minimum_achieved_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minimum_achieving_agents', to='ecommerce.order'),
        ),
    ]
