# Generated by Django 5.2.7 on 2026-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0012_agent_minimum_achieved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('upline', 'Upline Commission')], max_length=20),
        ),
    ]
