# Generated by Django 5.2.7 on 2026-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0013_alter_mlmtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('upline', 'Upline Commission'), ('pos_profit', 'POS Agent Profit'), ('service_profit', 'Society Agent Profit')], max_length=20),
        ),
    ]
