# Generated by Django 5.2.7 on 2026-06-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('mlm', '0014_alter_mlmtransaction_transaction_type'),
        ('pos', '0050_posprofitsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mlmtransaction',
            name='pos_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_transactions', to='pos.salesmaster'),
        ),
        migrations.AlterField(
            model_name='mlmtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_transactions', to='ecommerce.order'),
        ),
    ]
