# Generated by Django 5.2.7 on 2026-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0015_alter_mlmtransaction_options_mlmtransaction_pos_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_pos_branch_agent',
            field=models.BooleanField(default=False, help_text='True = auto-created from POS branch signal (already eligible). False = manually registered POS agent (normal rules apply).'),
        ),
    ]
