# Generated by Django 5.2.7 on 2026-09-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_orderitem_mlm_commission_processed'),
        ('mlm', '0016_agent_is_pos_branch_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmtransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mlm_transactions', to='ecommerce.orderitem'),
        ),
    ]
