# Generated by Django 5.2.7 on 2026-09-25 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_orderitem_delivered_at'),
        ('mlm', '0017_mlmtransaction_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='minimum_achieved_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minimum_achieving_agents_item', to='ecommerce.orderitem'),
        ),
    ]
