# Generated by Django 5.2.7 on 2026-05-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechIndustryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tech_industry_services/multi/')),
            ],
        ),
        migrations.CreateModel(
            name='TechIndustryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=251)),
                ('location', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('contact_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tech_industry_services/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='tech_industry_services/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tech_services', to=settings.AUTH_USER_MODEL)),
                ('multi_images', models.ManyToManyField(blank=True, to='services.techindustryimage')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_services', to='ecommerce.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='TechIndustryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.techindustryservice')),
            ],
        ),
    ]
