# Generated by Django 5.2.7 on 2026-05-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_techindustryimage_techindustryservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechIndustryBigAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/techindustry-big/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechIndustrySmallAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='ads/techindustry-small/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slot',)},
            },
        ),
    ]
