# Generated by Django 5.2.7 on 2026-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_professionalbigad_professionalserviceimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saloonservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='techindustryservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travelagencyservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
