# Generated by Django 5.2.7 on 2026-06-06 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('services', '0005_gymservice_is_active_professionalservice_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='finance_services/multi/')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='Google Maps link', max_length=500)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='finance_services/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_services', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_services', to='ecommerce.vendor')),
                ('multi_images', models.ManyToManyField(blank=True, to='services.financeserviceimage')),
            ],
            options={
                'db_table': 'finance_service',
                'ordering': ['-created_at'],
            },
        ),
    ]
