# Generated by Django 5.2.7 on 2026-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_educationbigad_educationnewserviceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='parent_service',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Salon', 'Salon'), ('Hotel', 'Hotel'), ('Travel', 'Travel'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Tech Industry', 'Tech Industry'), ('restaurant', 'Restaurant'), ('Professional', 'Professional'), ('Real-Estate', 'Real-Estate')], max_length=50, verbose_name='Parent Service'),
        ),
    ]
