# Generated by Django 5.2.7 on 2026-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicesubcategory_parent_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantBigAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/restaurant-big/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicesubcategory',
            name='parent_service',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Salon', 'Salon'), ('Hotel', 'Hotel'), ('Travel', 'Travel'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Tech Industry', 'Tech Industry'), ('Restaurant', 'Restaurant'), ('Professional', 'Professional'), ('Real-Estate', 'Real-Estate')], max_length=50, verbose_name='Parent Service'),
        ),
        migrations.CreateModel(
            name='RestaurantSmallAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='ads/restaurant-small/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slot',)},
            },
        ),
    ]
