# Generated by Django 5.2.7 on 2026-06-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('services', '0011_restaurantbigad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(help_text='Restaurant business name', max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='Google Maps link', max_length=500)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('restaurant_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Restaurant rating out of 5', max_digits=3, null=True)),
                ('description', models.TextField(help_text='Restaurant description with HTML/Tax editor support')),
                ('tax_description', models.TextField(blank=True, help_text='Tax information with rich text editing', null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='restaurant_services/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_restaurant_services', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_services', to='ecommerce.vendor')),
            ],
            options={
                'verbose_name': 'Restaurant Service',
                'verbose_name_plural': 'Restaurant Services',
                'db_table': 'restaurant_service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_services/multi/')),
                ('restaurant_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_multi_images', to='services.restaurantservice')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantservice',
            name='multi_images',
            field=models.ManyToManyField(blank=True, to='services.restaurantserviceimage'),
        ),
    ]
