# Generated by Django 5.2.7 on 2026-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_restaurantservice_restaurantserviceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinquiry',
            name='service_category',
            field=models.CharField(choices=[('salon', 'Salon'), ('gym', 'Gym'), ('real_estate', 'Real Estate'), ('travel_agency', 'Travel Agency'), ('finance', 'Finance'), ('tech', 'Tech Industry'), ('hospitality', 'Hospitality'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('professional', 'Professional'), ('work_place', 'Work Place'), ('restaurant', 'Restaurant')], max_length=50),
        ),
    ]
