# Generated by Django 5.2.7 on 2026-06-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_serviceinquiry_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinquiry',
            name='service_category',
            field=models.CharField(choices=[('salon', 'Salon'), ('gym', 'Gym'), ('real_estate', 'Real Estate'), ('travel_agency', 'Travel Agency'), ('finance', 'Finance'), ('tech', 'Tech Industry'), ('hotel', 'Hotel'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('professional', 'Professional'), ('work_place', 'Work Place'), ('restaurant', 'Restaurant')], max_length=50),
        ),
    ]
