# Generated by Django 5.2.7 on 2026-06-23 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('services', '0014_alter_serviceinquiry_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_services/multi/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(help_text='Hotel business name', max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='Google Maps link', max_length=500)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gmail_id', models.EmailField(blank=True, max_length=255, null=True)),
                ('hotel_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Hotel rating out of 5', max_digits=3, null=True)),
                ('description', models.TextField(help_text='Hotel description with rich text editor')),
                ('room_category', models.CharField(choices=[('manual', 'Manual'), ('premium', 'Premium')], default='manual', help_text='Room category type - Manual or Premium', max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotel_services/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hotel_services', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', to='ecommerce.vendor')),
                ('multi_images', models.ManyToManyField(blank=True, to='services.hotelserviceimage')),
            ],
            options={
                'verbose_name': 'Hotel Service',
                'verbose_name_plural': 'Hotel Services',
                'db_table': 'hotel_service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='e.g., Deluxe Room, Suite, Standard Room', max_length=100)),
                ('person', models.PositiveIntegerField(help_text='Number of persons')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price per night in INR', max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='services.hotelservice')),
            ],
            options={
                'db_table': 'hotel_room_type',
                'ordering': ['id'],
            },
        ),
    ]
