# Generated by Django 5.2.7 on 2026-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_hotelserviceimage_hotelservice_hotelroomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBigAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/hotel-big/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelSmallAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='ads/hotel-small/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('slot',)},
            },
        ),
    ]
