# Generated by Django 5.2.7 on 2026-06-30 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecommerce', '0026_alter_customerprofile_email_and_more'),
        ('services', '0016_hotelbigad_hotelsmallad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ✅ STEP 1: Remove OLD unique_together — STATE ONLY.
        # MySQL doesn't actually have this exact named constraint
        # (that's what caused "Found wrong number (0) of constraints"),
        # so we update Django's migration state without touching the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='servicereview',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),

        # ✅ STEP 2: Add the new order_item column (real DB change)
        migrations.AddField(
            model_name='servicereview',
            name='order_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='ecommerce.orderitem',
            ),
        ),

        # ✅ STEP 3: Add the new 4-field unique_together for real.
        # Fresh constraint, nothing old to find/delete — safe.
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('user', 'content_type', 'object_id', 'order_item')},
        ),

        # ✅ STEP 4: Add new indexes (real DB change)
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['content_type', 'object_id'], name='services_se_content_11c515_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='services_se_user_id_3e885f_idx'),
        ),
    ]