# Generated by Django 5.2.7 on 2026-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_is_agent_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent_approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
