# Generated by Django 5.2.7 on 2026-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_agent_approved_at_remove_user_is_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer Only'), ('agent', 'Agent Only'), ('both', 'Both Customer and Agent')], default='customer', max_length=20),
        ),
    ]
