# Generated by Django 5.2.7 on 2026-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('vendor', 'Vendor'), ('branch', 'Branch'), ('agent', 'Agent'), ('customer', 'Customer'), ('both', 'Customer + Agent')], default='customer', max_length=20),
        ),
    ]
