# Generated by Django 5.2.7 on 2026-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer Only'), ('agent', 'Agent Only'), ('both', 'Both Customer and Agent'), ('vendor', 'Vendor'), ('branch', 'Branch'), ('superadmin', 'Super Admin'), ('branch_customer', 'Branch + Customer'), ('branch_agent', 'Branch + Agent'), ('branch_both', 'Branch + Customer + Agent')], default='customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer Only'), ('agent', 'Agent Only'), ('both', 'Both Customer and Agent'), ('vendor', 'Vendor'), ('branch', 'Branch'), ('superadmin', 'Super Admin'), ('branch_customer', 'Branch + Customer'), ('branch_agent', 'Branch + Agent'), ('branch_both', 'Branch + Customer + Agent')], default='customer', max_length=30),
        ),
    ]
