# Generated by Django 5.2.7 on 2026-06-11 05:19

from django.db import migrations, models
import uuid


def fix_duplicate_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')

    # Step 1: Empty email "" → None karo
    for u in User.objects.filter(email=""):
        u.email = None
        u.save(update_fields=['email'])

    # Step 2: Duplicate emails → unique banao
    from django.db.models import Count
    duplicates = (
        User.objects.values('email')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .exclude(email=None)
    )
    for dup in duplicates:
        users = User.objects.filter(email=dup['email']).order_by('id')
        for u in users[1:]:  # pehla rakho, baaki fix karo
            u.email = f"dup_{u.id}_{uuid.uuid4().hex[:6]}@fix.local"
            u.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role_alter_user_user_type'),
    ]

    operations = [
        # ← PEHLE DATA FIX
        migrations.RunPython(fix_duplicate_emails, migrations.RunPython.noop),

        # ← PHIR FIELD ALTER
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]